Basic Product CRUD with User Permissions
aminasaif0/Rails-E-commerce- pull request #2
Opened 2023-12-22 06:39 UTC by aminasaif0

2023-12-22 09:51 UTC, salman-haider-confiz requested changes

2023-12-22 09:51 UTC, salman-haider-confiz commented on Gemfile
> +  gem "byebug"
Always lock the Gem version.

2023-12-22 09:51 UTC, salman-haider-confiz commented on app/helpers/products_helper.rb
> +end
No Need to create Helper if we are not using it.

2023-12-22 09:51 UTC, salman-haider-confiz commented on app/models/concerns/role_check.rb
> +    extend ActiveSupport::Concern
indentation issue

2023-12-22 09:51 UTC, salman-haider-confiz commented on app/models/role.rb
> +    has_many :roles_users, dependent: :destroy
This table name should be like "user_roles"

2023-12-22 09:51 UTC, salman-haider-confiz commented on app/models/user.rb
> +  has_many :roles_users
same here

2023-12-22 09:51 UTC, salman-haider-confiz commented on test/fixtures/roles_users.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
Remove this file.

2023-12-22 09:51 UTC, salman-haider-confiz commented on test/models/role_test.rb
> +end
Do add test cases as well

2023-12-22 09:51 UTC, salman-haider-confiz commented on test/models/roles_user_test.rb
> +end
Do add testcases as well

2023-12-22 09:51 UTC, salman-haider-confiz commented on app/models/user.rb
>  end
Do we have any validation check for User table?

2023-12-26 11:18 UTC, saadali7865 approved these changes

2023-12-26 11:18 UTC, saadali7865 commented on app/controllers/products_controller.rb
> +      end
make it one liner

2023-12-26 11:18 UTC, saadali7865 commented on app/controllers/users_controller.rb
> +  end
Add space or proper indentation

2023-12-26 11:18 UTC, saadali7865 commented on app/helpers/carts_helper.rb
> +end
remove this file

2023-12-26 11:18 UTC, saadali7865 commented on app/models/concerns/role_check.rb
> +  end
def is_admin?
  roles.exist?(admin)
end

2023-12-26 11:18 UTC, saadali7865 commented on app/policies/application_policy.rb
> +  class Scope
What is Scope class

2023-12-26 11:18 UTC, saadali7865 commented on app/views/layouts/application.html.erb
> +    </style>
Move css to separate file

2023-12-26 12:20 UTC, merged